### ISSUE TITLE
The tool leaves leftover Docker images after image generation

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#31] opened 2019-06-18 16:48 UTC
After the tool `imagetool create` performs its job, there are leftover Docker images in the system. 

It may be necessary to check them from time to time to remove them to prevent going out of space in the system. [The quickstart](https://github.com/oracle/weblogic-image-tool/blob/master/site/quickstart.md) of the tool's documentation ([cleanup](https://github.com/oracle/weblogic-image-tool/blob/master/site/quickstart.md#cleanup) section) suggests to run `docker rmi $(docker images --filter "dangling=true" -q --no-trunc)` to remove the leftover images. 

But, maybe the tool could keep track of the generated intermediate images and clean them by itself?

**Comment by ddsharpe** [comment] 2019-07-12 15:55
Based on the issues filed over on Docker, leaving the intermediate layers is the behavior that Docker desires.  There have been quite a few complaints on the Docker page, but those issues keep getting rejected as "working as designed/desired".  I have an idea for a workaround based on some of the comments over on Docker.  I will try a couple of them out and see which one works best.  Since this is the "desired" behavior according to Docker people, I will look at making this an optional flag to cleanup intermediate images, but the default will be to leave them.  Things like "docker system prune" and the "docker rmi" command you mention are good ways to cleanup for now.

**Comment by ddsharpe** [comment] 2019-10-10 20:54
Fixed by PR #95

**Closed by ddsharpe** 2019-10-10 20:54 UTC
